<noscript>
  <a href="$base$/_login">Login</a>
  <a href="$base$/_logout">Logout</a>
</noscript>
<div class="list-group mt-3">
  <a id="loginlink" class="list-group-item list-group-item-action" href="/_login">
    <i class="fa fa-sign-in-alt fa-fw mr-2"></i>
    <span>Log in</span>
  </a>
</div>
<div class="list-group mt-3 d-none">
  <a id="logoutlink" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center" href="/_logout">
    <span>
      <i class="fa fa-sign-out-alt fa-fw mr-2"></i>
      <span>Log out</span>
    </span>
    <span class="badge badge-secondary badge-pill p-2">
      <i class="fa fa-user fa-fw mr-1"></i>
      <span id="logged_in_user"></span>
    </span>
  </a>
</div>
